branches:
  except:
    - /appveyor/
language: perl
matrix:
  include:
    - perl: "5.22"
    - perl: "5.20"
    - perl: "5.18"
    - perl: "5.16"
    - perl: "5.14"
    - perl: "5.12"
    - perl: "5.10"
    - perl: "5.8"
    # Actually the perl here does not matter
    - perl: "5.14"
      env: USE_SYSTEM_PERL=1
sudo: false
before_install:
 - if [ "$USE_SYSTEM_PERL" = 1 ]; then perlbrew off; fi
script:
 - perl Makefile.PL && env HARNESS_TIMER=1 make disttest
